### ISSUE TITLE
Images of products are not showing up,when i'm running this product locally.please help me out sir

### ISSUE THREAD

**Issue by abhay2701** [rahulmkadam92/Ecommerce#2]
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>B0ED41076086F3CA</RequestId>
<HostId>
G8R0jOF2cYx4DpmpiavFvgkLYWtFjIR8hCMenP1adYrCRdFIMGvgu5zw9kB6a+KtIYXMVtdkdK0=
</HostId>
</Error>

this error is coming when i'm opening the image in new tab?

**Comment by niladri6** [comment]
server is not running. It will throw this error: 

D:\Node.js Practice\test\Ecommerce-master\server>node server.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Node.js Practice\test\Ecommerce-master\server\routes\main.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Node.js Practice\test\Ecommerce-master\server\server.js:30:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
