### ISSUE TITLE
Server is not running

### ISSUE THREAD

**Issue by niladri6** [rahulmkadam92/Ecommerce#3]
server is not running. It will throw this error:

D:\Node.js Practice\test\Ecommerce-master\server>node server.js
internal/modules/cjs/loader.js:638
throw err;
^

Error: Cannot find module 'async'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:690:17)
at require (internal/modules/cjs/helpers.js:25:18)
at Object. (D:\Node.js Practice\test\Ecommerce-master\server\routes\main.js:5:15)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:690:17)
at require (internal/modules/cjs/helpers.js:25:18)
at Object. (D:\Node.js Practice\test\Ecommerce-master\server\server.js:30:20)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by zac11** [comment]
Just install `npm i async` inside the `server` directory and it will work

**Comment by kittupriyatham** [comment]
I couldn't execute npm install command in the server folder.
I am getting this error

C:\Users\lenovo\OneDrive - K L University\Desktop\peregrine-deliveries-master\server>npm install      
npm ERR! Unexpected end of JSON input while parsing near '...VBF\np3zbCRzr0ebIHtb4'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2020-12-12T12_59_26_592Z-debug.log

I don't understand this part. '...VBF\np3zbCRzr0ebIHtb4'

**Comment by hafsa56** [comment]
![image](https://user-images.githubusercontent.com/22784437/185101549-d51d153f-04e0-4990-9269-010e04849e13.png)
